apiVersion: v1
kind: Pod
metadata:
  name: nginx-bite
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest  
      ports:
        - containerPort: 80
      securityContext:
        privileged: true     # absolument pas nécessaire
      resources: {}
      env:
        - name: NGINX_ENV
          value: "une chose géaaannnnteee"
  restartPolicy: Always
